# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='joining', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Party'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='exchange.Participant'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Party'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='exchange.Participant'),
        ),
    ]
