# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0004_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('party', 'user')]),
        ),
    ]
