# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20170117_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Party', unique=True),
        ),
    ]
