# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20170118_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Party'),
        ),
    ]
