# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20170118_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(default='Invited', max_length=255),
        ),
    ]
