# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.CharField(choices=[('JOINED', 'joined'), ('INVITED', 'invited'), ('LEFT', 'left')], default='INVITED', max_length=255),
        ),
    ]
