# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20170124_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('JOINED', 'joined'), ('INVITED', 'invited'), ('LEFT', 'left')], default='INVITED', max_length=255),
        ),
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.CharField(choices=[('JOINING', 'joining'), ('STARTED', 'started')], default='JOINING', max_length=255),
        ),
    ]
